###Discussion

We used a large global database (ForC), containing an unprecedented amount of data representing all major forest types (Fig. 1) and the nine most significant forest autotrophic carbon flux (FACF) variables (Table 2), to comprehensively explore how C cycling in mature, undisturbed forests varies with latitude and climate on a global scale. We test a suite of hypotheses, including many previously posed (Table 1), with more data and standardisation for factors that have not always been controlled for (*e.g.*, stand age, flux components measured) to gain a stronger understanding of climatic effects on FACF. We show that, across all nine FACF variables analyzed, C cycling decreases linearly with latitude (Figs. 2-3)--a finding that confirms multiple previous studies (**REFS**) but contradicts the idea that productivity of temperate forests rivals that of tropical forests (**REFS**). The FACF variables increase in proportion to one another, with no differences in allocation detectable at this global scale and with component fluxes summing appropriately to larger fluxes (Fig. 3), indicating no major, systematic omissions or overestimations of flux components. However, we did detect a tendency for greater variability among subsidiary C fluxes (e.g., *$ANPP_woody$*, *$BNPP_{fine root}$*; Fig. 2; **some SI table?**; **discussed below??**). Climate explains a significant proportion of variation in all C fluxes analyzed (albiet less for subsidiary fluxes), with temperature variables being the best predictors of FACF on this global scale (Figs. 4-5). While other climate variables are significant predictors of FACF, none of them improve on the explanatory power of temperature-related variables in general or MAT specifically (Fig. 5). Water availability is an important factor in explaining FACF on a global scale: we find a positive influence of precipitation at low MAP, with saturation at higher levels of MAP (Fig. 5b) and a significant interaction between MAT and MAP for seven of the nine variables analyzed (Fig. 4). Temperature seasonality and growing season length are closely correlated with MAT and are strong predictors of FACF (Fig. 5e-f), though growing season length doesn't improve upon MAT as a predictor. Within the growing season, the influence of climate on C cycling is smaller but still significant for a number of carbon fluxes (**some SI table?**). These findings clarify the big picture of how FACF varies with latitude and climate on a global scale.

Past studies have differed in their conclusions regarding the relationship between productivity and latitude or its correlates (**REFS**)--quite possibly because of lack of standardization with respect to stand age and disturbance history. Our findings indicate that, among mature, undisturbed stands, FACF is unambiguously highest in the tropical regions, and the relationship is approximately linear (Figs. 2-3). This contrasts with suggestions that productivity of temperate forests is similar to that of tropical forests (**REFS**). Such observations may be attributable to the fact that temperate forests are predominantly secondary and of younger age than tropical forests (**REF**), so analyses comparing across latitudinal gradients without strict control of stand age tend to be comparing younger temperate stands with older tropical (and often boreal) forests ([Poulter et al. 2018-DOI:10.1594/PANGAEA.889943](http://pure.iiasa.ac.at/id/eprint/15361/)). Because C allocation varies with stand age (**REFS (KAT/NOBBY)**), age differences may introduce systematic biases into analyses of FACF across latitude or global climatic gradients. For example, woody productivity tends to be higher in rapidly aggrading secondary stands than in old-growth forests, where proportionally more C is allocated to respiration (**REFS**) [*purpose for respiration/ other compenents (**REFS????- NOBBY?**)]. By constraining our analysis to stands ≥100 years old with no record of major recent disturbance, we have clarified the shape of the relationship between FACF and latitude. 


[**THIS PARAGRAPH NEEDS ATTENTION!**]. We show that fluxes are broadly consistent in their responses to climate drivers on the global scale (with the exception of some differences in MAT-MAP interactions; Fig. 4), with no major trends in C allocation among the variable pairs tested (Fig. 2; **Some SI table**). *This finding does not support some of the dominant current understanding, with significant implications for our understanding of FACF responses to climatic warming.* Of particular interest are the relationships between $GPP$ and respiration ($R_{auto}$, $R_{root}$) or net primary productivity ($NPP$, $ANPP$, $BNPP$). The dominant current understanding is that *respiration responds more strongly to temperature than does photosynthesis (**REFS(KAT)**)*, and that carbon use efficiency ($CUE$= $NPP$/$GPP$=($GPP$-$R_{auto}$/$GPP$) is lowest in the tropics (**REFS(KAT)**). The latter understanding is driven by observations of low $CUE$ in old-growth tropical forests relative to extratropical forests [@de_lucia_forest_2007; @anderson-teixeira_carbon_2016] (**REFS(KAT)**), but our analysis suggests that these low values may more appropriately be attributed to the fact that these forests are old than to their climate. Indeed, $CUE$ is known to decline with forest age ([@de_lucia_forest_2007];**REFS(NOBBY)**). Whereas autotrophic respiration responds more strongly to temperature than does photosynthesis on short time scales (**REFS(KAT)**), our findings indicate that annual C allocation to respiration is roughly independent of temperature.  [There is some indication that $GPP$ may have a somewhat steeper and less variable relationship to latitude and temperature than does $ANPP_{woody-stem}$ (Fig. 2; see also Larjavaara & Muller-Landau (2011)?), but standardized slopes are not signficnatly different (**??-BECKY**). (**Helene, maybe comment on Larjavaara & Muller-Landau (2011)?**). ] While our analysis indicates that climate shapes most FACFs in similar ways on the global scale, careful methodological standardization across a consistent set of mature forest sites could potentially reveal modest but potentially signficant trends in carbon allocation along global climatic gradients. 
[There is evidence that allocation between carbon fluxes does vary with factors such as stand age [@litton_carbon_2007], nutrient availability [@litton_carbon_2007; @gill_belowground_2016], forest structure [@taylor_greater_2019], elevation [@moser_elevation_2011], and water availability [@newman_above-_2006]. That we do not see consistent patterns of variation in allocation across global climatic gradients indicates that the pressures influencing shifts in allocation between fluxes occur on local scales and/or in response to factors other than mean climate, including inter- and intra-annual climiatic fluctuations. ]  


One interesting observation was that climate explains more variation in the major fluxes ($GPP$, $NPP$, $R_{auto}$ - latitude R^2≥48%) than in subsidiary fluxes (latitude R^2<27% for $BNPP_{fine.root}$, $R_{auto-root}$,$ANPP_{woody-stem}$) (Fig. 2; **some SI table?**). There are two non-exclusive potential explanations for this. First, it may be that methodological variation is larger relative to flux magnitude for some of the subsidiary fluxes. Belowground fluxes in particular are difficult to quantify, and measurement methods for the belowground fluxes considered here may be measured through fundamentally different approaches (*e.g.*, **minirhizotrons, ingrowth cores, or sequential coring for $BNPP_{root-fine}$; root exclusion, stable isotope tracking, or gas exchange of excised roots for $R_{auto-root}$**), and sampling depth is variable and often insufficient to capture the full soil profile. $ANPP_{woody-stem}$, which is also poorly explained by latitude or climate, is more straightforward to measure but is subject to variability introduced by differences such as biomass allometries applied, minimum plant size sampled, and exclusion or inclusion of branch fall (**?- Becky, did we end up lumping? REF**). However, methodological variation and uncertainty affects all of fluxes considered here--not necessarily any less than the aforementioned, and some of the larger fluxes that vary more strongly with respect to climate (ANPP, NPP) are estimated by summing uncertain component fluxes. Second, differences among variables in the proportion of variation explained by climate could indicate that factors other than climate have significant influence over subsidiary fluxes. *This is consistent with the results we find for allocation between fluxes: although climate has a significant influence on subsidiary fluxes, it is not the only factor that is important, and many other local- and regional-scale factors  influence the way carbon is allocated between subsidiary fluxes. We would expect that this would reduce the strength of the effect of climate on subsidiary fluxes.* [**work on this second part, add refs**]

[paragraph discussing climate drivers. MAT as best, although the advantage of MAT over other temperature variables may in part be because of better quality data . Regarding seasonality, FACF and climate data lack the temporal resolution required to sort this out. We find no support for the argument that correcting for growing season length improves the explanatory power.]

[Despite the coarse resolution of this analysis, it holds some important implications for our understanding of how forest carbon cycling relates to climate and, by extension, how it is likely to respond to climatic warming. We see no evidence that there are major differences in how the various components of forest autotrophic carbon cycling relate to climate or, by extension, any distinct trends in C allocation across the global scale (Fig. 3). ]

~~~


Secondly, we emphasise that this study considers the relationship between productivity and climate on a coarse scale. Because of the nature of the ForC database, we were unable to access site-level MAT and MAP data for a number of sites, and lacked site-level data for other climate variables for all sites. As a result the climate data we used was primarily multi-year averages of annual climate measures accessed from global databases. While the quality of these data is high, we cannot expect that it captures detailed local variation in climate, and in particular will be unable to capture microclimate variation, which may have a strong influence on stand-level productivity. Although we find that MAT is the strongest predictor for climate, part of this effect may be a result of the higher-quality stand-level dataset available for MAT. With high-quality stand-level data for other climate variables we expect that their predictive strength would improve. 

Furthermore, we expect that temporal resolution of climate data affects our results. Productivity is known to vary on a seasonal and annual scale in response to variation in climate. Our analysis relies on long-term averages in both climate variables and forest productivity estimates, and as a result averages out a large proportion of this variation. Therefore we recognise that the strong short-term effects of climate on productivity are likely to be masked. The limitations of low temporal resolution are highlighted in our analysis of growing season length. We note that our estimate of growing season length is imprecise, being based on monthly temperature, precipitation, and evapotranspiration averages. With accurate stand-level measurements of growing season length, based on daily, not monthly, climate measures, we would expect to record a stronger correlation between growing season length and productivity.

There is strong evidence from our analyses that this increase in productivity towards the tropical regions is driven primarily by temperature-related effects. We find that temperature-related climate variables explain the highest proportion of variability in productivity. In contrast, we find that MAP is not a significant predictor of productivity, but does show a strong interaction with temperature. This indicates that the main mechanism through with precipitation influences productivity is in a secondary capacity, with its overall influence being mediated by the effects of temperature. This also suggests that although temperature explains a large proportion of variation, it cannot fully explain productivity alone, and a measure of water availability is necessary to fully understand patterns of productivity. This is likely to be significant in the future, as it suggests that the effects of a warming climate will be mediated through changes in precipitation regime. 

There is debate over whether productivity in regions with higher MAT is higher because productivity inherently increases with air temperature during growing season months, or because higher MAT is correlated with longer growing seasons. Our analysis suggests that length of growing season is a key factor in understanding latitudinal patterns in productivity. We find that length of growing season is strongly correlated with productivity. This is supported by the strong correlation between temperature seasonality and productivity, indicating that aseasonality and year-round growing seasons have a strong influence over productivity. 

These conclusions are supported by our analyses of the influence of climate within the growing season. We find much weaker correlations between climate variables and productivity when only growing season months are considered. There is evidence for a positive correlation between productivity and temperature for ANPP and ANPP~foliage~, suggesting that there is still a small positive effect of air temperature on productivity independent of growing season, however this effect is not significant for the remaining fluxes. This suggests that the primary positive effect of temperature on productivity is through the lengthening of the growing season in regions with higher MAT. However, we note that length of growing season is a less good predictor of productivity than MAT. As discussed above, this may be an artefact of imprecise estimation of length of growing season, however it does indicate that there are aspects of productivity explained by MAT which length of growing season alone cannot explain.



**[needs strong concluding paragraph]**

### Acknowledgements
Scholarly Studies
ForestGEO
DOE database

