---
title: "Response to reviews"
output: pdf_document
bibliography: library.bib
csl: global-change-biology.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
  
Dear Editor:

We are please to submit a revised version of our manuscript, "Global patterns of forest autotrophic carbon fluxes" (GCB-20-1713), for consideration for publication in *Global Change Biology*. We have addressed all points raised by the reviewers, as detailed below. The most significant changes include:

- We modified the presentation to clarify that this is intended as a high-quality quantitative review using a vastly expanded and standardized dataset, noting that it was never our intention to claim to be posing novel hypotheses. 

- We added some statements clarifying how our analysis improves upon previous similar analyses. Major improvements include sized of database, number of variables considered, and standardization of stand age, history, and management.

- We added discussion relating our results to the eddy-covariance literature on growing season length and highlighting some modeling implications.

Thank you for considering this revised version, and we look forward to your response.

Sincerely,

Kristina Anderson-Teixeira (on behalf of all coauthors)

\newpage
    
  

# Reviewer(s)' Comments to Author:

## Reviewer: 1

### Comments to the Author


Using 1,319 records from the Global Forest Carbon Database (ForC), authors of this manuscript explored the spatial pattern of several carbon flux. They found forest C fluxes decreases with absolute latitude. Among climatic variables, mean annual temperature and temperature seasonality were found to be the best univariate climatic predictors. They suggest their findings could improve understanding of forest carbon cycling under climate change. Overall, the manuscript is well written, but the findings seem not improving contemporary knowledge of forest carbon cycling, and the study appears to be a simple statistical analyses of literature data, which did not reveal the biological mechanisms lead to the detected pattern. Thus, I cannot recommend publishing this paper in GCB, but suggest the authors to consider a data journal like ESSD.


**Most of the points raised here are covered by more specific comments below, and our responses to these points follow those comments.** 

**We believe that one general problem may have been that the previous manuscript version didn't clearly communicate our intentions, which were not to pose novel hypotheses but to conduct a quantitative review of the subject using a vastly expanded and standardized dataset. While we feel that the text of the introduction made it clear that we weren't intending to present the hypotheses as novel, we have realized that a quick review of Table 1 in isolation would give the false impression that we intended these analyses as novel hypothesis tests. We have taken some steps to improve this aspect:**

**1. We modified Table 1, labeling the questions as "review questions" and clarifying that many of the hypotheses have been previously tested, citing relevant publications.**

**2. We have made the following revisions to the language in the abstract and introduction to clarify that our intention is to provide a quantitative review that clarifies uncertainty in these relationships:**  

- **Abstract: "Here, we draw upon 1,319 records from the Global Forest Carbon Database (ForC), representing all major forest types and the nine most significant autotrophic carbon fluxes, to comprehensively ~~explore~~ *review* how annual C cycling in mature, undisturbed forests varies with latitude and climate on a global scale."** 
- **Introduction: "In order to approach this broad topic, we organize the major gaps in our knowledge under five broad review questions and corresponding predictions, many derived from the findings of previous studies (Table 1)."**

**One point above that is not addressed below is that we present "simple statistical analyses". While we concur that the analyses are relatively simple, that does not preclude their being appropriate, informative, and sufficient. They represent several substantive advances over past analyses of this type:**

-  **They are underlain by a large, standardized database that accounts for factors such as stand age and management, which have not always been accounted for.**

-  **We use mixed effects model to account for random effects of location (plot nested within geographic area), thereby accounting for potential pseudoreplication, which has not always been done in the past.**

-  **We examined nine carbon fluxes and relationships among them--more than has been concurrently analyzed in the past.**

-  **For each flux variable, we tested a wide range of models: univariate responses to 12 climate variables (3 functional fit types for each), along with multivariate models (MAT x MAP for all, along with other combinations not presented).** 

**Thus, although the analyses are simple, we believe them to be appropriate and sufficient, with their novelty arising not from the analysis method itself but from the coverage and extent of the dataset.**

The analyses performed were too conventional that similar analyses with a smaller size of similar datasets have been performed a decade ago.

**This statement suggests a lack of perspective on the scope of our analysis relative to previous studies. Whereas most studies consider at most a few flux variables, ours considers nine. The most comprehensive similar study is @luyssaert_co_2007, which was published in *GCB* more than a decade ago, was based on a database <25% the size of the ForC version used here, did not control for effects of stand age/ disturbance history, and examined latitudinal/ global climatic trends in only three variables. We note in particular that in @luyssaert_co_2007, mean stand age was extremely variable across biomes, and while mean stand age in tropical forests was >100 years (old growth) in all but one extra-tropical biome, mean stand age was <100. This is likely to elevate productivity estimates for extra-tropical biomes, highlighting the need for a comprehensive, standardised dataset for analysis.  Thus, the current analysis will be at the clear forefront of studies examining correlations between forest carbon flux and climate at the global scale.**

**To help clarify the scope of this analysis to readers, we added the following statement to the last paragraph of the introduction: "Our analyses represent a major step forward in relation to previous work [e.g., @luyssaert_co_2007] in that we examine global climatic trends in more variables (9 vs. $\le$ 3), draw from a much larger database (>4 times more records analyzed), and control for the effects of stand age, disturbance, and management."**

Forest C fluxes decreasing with latitude was also not a new finding. The author suggest that it contradicts with some previous studies finding that “net primary productivity of temperate forests rivals that of tropical forests”. However, those high NPP in temperate forests could result from high rates of nitrogen deposition or forest plantation (Yu et al., 2014), which are in different context with the mature, undisturbed forests studied in this manuscript.

**We agree that these results are not surprising to many of us, and state in the introduction that productivity decreases with latitude. Yet, as also noted in the introduction, the form of this relationship is less clear, and contradictory papers have been published in high-profile journals in the last 15 years [@luyssaert_co_2007; @huston_global_2009;  @gillman_latitude_2015]. A crucial part of science is built on high-quality synthesis that clarifies current understanding and probes for unexpected relationships, which is the goal here-- as opposed to testing this as a novel hypothesis.** 

**As this comment identifies, results from previous studies were complicated by other effects. The power of this synthesis lies in how it standardises for the effects of stand age and disturbance history, unambiguously clarifying these relationships. We have added text to the introduction to highlight the importance of standardisation of the dataset: "C flux and allocation vary with stand age, disturbance, and management [@de_lucia_forest_2007; @yu_high_2014; @fernandez-martinez_spatial_2014; @simova_enigma_2017], making clear latitudinal patterns difficult to discern without standardization of the dataset."**

**Thank you for highlighting the paper by Yu et al. (2014). We have cited this at several points in the text.**

It is not surprising that MAT was found to be the good climate variables explaining forest C fluxes, since MAT has strong correlation with latitudes. Our contemporary knowledge on forest carbon cycling has moved well beyond using mean climatic variable to extrapolate or guess the response of forest carbon cycling to climate change. The spatial gradient do not necessarily represent the response of forests to climate change. The main implications highlighted in the Abstract is not well supported by the results presented.

**We agree, and fully acknowledge in the paper, that this study does not reveal the biological mechanisms. Further, we do not argue that the spatial gradient represents the response of forests to climate change, as clearly discussed in the final paragraph of the discussion. However, we do argue that elucidating broad-scale patterns in C cycling across climatic gradients is a complementary approach to addressing a challenging problem [*sensu* @anderson-teixeira_altered_2013, *GCB*]. We note that studies using this approach have been published recently in *Nature* [@cook-patton_mapping_2020], *Science* [@sullivan_long-term_2020],  *GCB* [@trugman_climate_2019], *JGR* [@li_dissimilatory_2019],  *Scientific Reports* [@chen_spatial_2019], and as a Tansley review in *New Phytologist* [@mullerlandau_patterns_2020].**

**We also agree that spatial gradients do not necessarily represent the response of forests to climate change, and have made some changes to to ensure that we are not giving that message:**

- **Abstract: "~~In a period of accelerating climatic change, this improved understanding of the fundamental climatic controls on forest C cycling sets a foundation for understanding patterns of change.~~  In an era when forests will play a critical yet uncertain role in shaping Earth's rapidly changing climate, our synthesis provides a foundation for understanding global patterns in forest C cycling."**
- **Discussion: "~~Our analysis clarifies how annual forest autotrophic C fluxes vary with latitude and climate on a global scale, with some important implications for how forest C cycling relates to climate and, by extension, how it is likely to respond to climatic warming.~~ Our analysis clarifies how annual forest autotrophic C fluxes vary with latitude and climate on a global scale. " **

While I commend the authors’ efforts to harmonize the dataset, I found the paper lacks the novelty and significance to be published in GCB. A data-oriented journal is a more suitable place for this paper.

**This suggestion is inappropriate for two reasons. First, the hypothesis-testing analyses presented here would be unsuitable for a data journal. Second, the ForC database is already published [tropical portion only in @anderson-teixeira_carbon_2016, *GCB*; full database as a data paper in Anderson-Teixeira et al. @anderson-teixeira_forc_2018, *Ecology*]. This fact is prominently cited in the last paragraph of the introduction and the first sentence of the methods.**


## Reviewer: 2

### Comments to the Author
    
In the manuscript “Global patterns of forest autotrophic carbon fluxes”, Morgan et al. examined the latitudinal and climatic dependences of various autotrophic fluxes of global mature and undisturbed forests, using a recent release of the ForC database. They reported that latitude and temperature are the best univariate predictor of mature forest carbon cycling, while the effect of temperature is modified by precipitation. Overall, I appreciate this thorough analysis of the novel ForC database (great work in making data publicly available!) and see no major flaws in the study, thus most of my comments below are meant to further improve the manuscript. My comments are below:

1. How does the result compare with previous studies based on eddy covariance (EC) measurements? Throughout reading the manuscript, I have been trying to reconcile what’s been reported based on EC data and what is presented in the ms. Though EC cannot tell us much about NPP and other small fluxes, it did have a better (perhaps just marginally) spatial and temporal representation of forests. In particular, EC data has suggested that net carbon uptake is primarily dependent on carbon uptake period (Churkina et al. 2005, but see Fu et al. 2019 and Zhou et al. 2016), and increasing temperature can lengthen the growing season to enhance GPP and NEP (Keenan et al., 2014). The current study suggests that “growing season length is never the best predictor”. What do you think cause the difference between the two streams of evidence, and why MAT and latitude serves as a better predictor than growing season length? I do not ask for further analysis necessarily, but just feel the discussion could be expanded a bit on previous EC studies about the dominant control of forest carbon flux.

**Thank you for the excellent suggestion to expand the discussion of growing season length around the references given. We have re-written the paragraphs in the introduction and the discussion dealing with this issue, now citing the references listed in the comment above.**

2. A key conclusion is “no detectable differences in allocation across latitude or climates”, however, I do not see a strong evidence for that presented in the main text – Fig.S3 does show several allocation indicators though no statistics are provided. Fig. 2 shows that C fluxes increase approximately in proportion to one another, but that does not necessarily mean allocation is unchanged across latitude or climates.

**We found no significant relationships between flux ratios (allocation to fluxes) across latitude and three climate variables tested, and as a result have not presented figures illustrating this in the main article. We state that these results were non-significant (p>0.05) in the results section. We have updated the Fig. S3 legend to clarify that none of the fits are significant (and therefore no statistics are presented).**

3. Implication for models. I think it is nice for the authors to report that carbon flux of mature forest is primarily dependent on MAT or latitude. But how much could this advanced knowledge help us improve global simulation of forest carbon cycling. I’d be very curious to see if the state-of-the-art models demonstrate a similar or different functional response of carbon flux to MAT/latitude, and what is the possible reason for that. I think by tapping into this question (even just in discussion) will make the study be of interest to a wider audience.

**We have added the following comments on models to the discussion:**
- **Discussion: "We find no significant trend in the allocation of $GPP$ between production and respiration across latitude or climate ($NPP$:$R_{auto}$; Fig. S3), counter to the idea that tropical forests have anomalously low $CUE$ [@de_lucia_forest_2007; @malhi_productivity_2012; @anderson-teixeira_carbon_2016], *as predicted by most models* [@collalti_forest_2020]. In contrast, @collalti_forest_2020 found that forest production efficiency increased with temperature--a finding that is consistent in direction with the insignificant trends observed here (Fig. S3)."** 
- **Discussion: "The significant variation in C fluxes as a function of stand age has implications for ecosystem models. Ecosystem modelling approaches may neglect age-related effects, or assume stand equilibrium [see e.g. @yu_high_2014; @collalti_forest_2020]. Our results highlight the importance of incorporating stand age into ecosystem models; without this, models are likely to be vulnerable to bias in global C flux projections."**
- **Last sentence of discussion: "In the meantime, understanding the fundamental climatic controls on annual C cycling in Earth's forests sets a firmer foundation for understanding global-scale forest C cycling and benchmarking the models [@fer_beyond_2021] used to predict forest responses and feedbacks to accelerating climate change."**

Minor comments:

1. it is unclear in the method about how to calculate “temperature/precipitation seasonality”. Is it the standard deviation of monthly temperature/precipitation in a year?

**We have added brief definitions of these in the text (methods section), and refer readers to Table S1 for detailed information.**

2. In Table S3, does the R2 come from the univariate linear model or the multivariate model?

**We have adjusted table column names to clarify.**

3. Perhaps add R2 and p value in Fig. S3. Additionally, could you add the NPP to GPP ratio (CUE) as CUE is a quite often used allocation indicator.

**We have added a legend to clarify that none of the fits are significant (and therefore no statistics presented). We have chosen not to add CUE to the figure, as analysis of proportions (NPP/GPP) would require a different statistical approach than analysis of ratios. However, we have added text to the Fig. S3 legend to clarify that we interpret these results in terms of variation in CUE.**

4. L201 - To study the interactive effect of MAT and MAP, do you use MAT, MAP and MATxMAP as three predictors in a multivariate model or just MATxMAP in a linear model?

**We have clarified this in the text: "An interactive model containing a $MAT$ x $MAP$ interaction was accepted when $\Delta$AIC >2 relative to a null including $MAT$ and $MAP$ as fixed effects."**

5. I am also wondering about the representation of tropical and extra-tropical forests in the samples. One solution is to add a biome basemap in figure 1. If tropical forest stands are generally older than the extra-tropical forest stands (according to “Histogram_of_Stand_age” in the ForC database), then perhaps there is a need to standardize samples by stand ages when studying allocation.

**While ForC contains information on precise stand ages for many temperate forests (typically estimated from tree-rings), this information is typically unavailable for tropical forests, and so these forests are often recorded simply as 'old-growth' or 'undisturbed'. This means that they are believed to be older than 100 years of age, but the precise age is unknown. As a result, it is unfortunately not possible to standardise this dataset by age beyond 100 years, and so we treat all forests in the analysis as mature forests, assuming minimal effect of age beyond 100 years.** 

**To clarify this to readers, we have added the following statement: "To reduce any biasing effects of stand age, we included only stands of known age $\ge$ 100 years and those described by terms such as "mature", "intact", or "old-growth", *noting that ages of mature tropical forests are typically unknown because most tropical trees cannot be easily dated using tree-rings*."**

6. Fig. S6. Spell out “T seas” and “P seas” in the caption.

**We have made this edit.**

Churkina, G., Schimel, D., Braswell, B. H., & Xiao, X. (2005). Spatial analysis of growing season length control over net ecosystem exchange. Global Change Biology, 11(10), 1777–1787. https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1111%2Fj.1365-2486.2005.001012.x&data=02%7C01%7Cmullerh%40si.edu%7C95d13ecc18f5461cbe2408d858c4b0a9%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637356949086641203&sdata=fDBebq%2B1eqPsq2NDNe6zmEveEmfKtHpioWsoJn9yT%2BM%3D&reserved=0

Fu, Z., Stoy, P. C., Poulter, B., Gerken, T., Zhang, Z., Wakbulcho, G., & Niu, S. (2019). Maximum carbon uptake rate dominates the interannual variability of global net ecosystem exchange. Global Change Biology, gcb.14731. https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1111%2Fgcb.14731&data=02%7C01%7Cmullerh%40si.edu%7C95d13ecc18f5461cbe2408d858c4b0a9%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637356949086641203&sdata=aves%2BnxrjhGzFBzrXmb0c%2FXrEk0uku%2BwjHJJZqrF9v0%3D&reserved=0

Keenan, T. F., Gray, J., Friedl, M. A., Toomey, M., Bohrer, G., Hollinger, D. Y., … Richardson, A. D. (2014). Net carbon uptake has increased through warming-induced changes in temperate forest phenology. Nature Climate Change, 4(7), 598–604. https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1038%2Fnclimate2253&data=02%7C01%7Cmullerh%40si.edu%7C95d13ecc18f5461cbe2408d858c4b0a9%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637356949086641203&sdata=905OIXZQpS%2BRJ7xNVE1dakWAtdPrEl2gIk1PeTxWO%2Bk%3D&reserved=0
    
Zhou, S., Zhang, Y., Caylor, K. K., Luo, Y., Xiao, X., Ciais, P., … Wang, G. (2016). Explaining inter-annual variability of gross primary productivity from plant phenology and physiology. Agricultural and Forest Meteorology, 226–227(October), 246–256. https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1016%2Fj.agrformet.2016.06.010&data=02%7C01%7Cmullerh%40si.edu%7C95d13ecc18f5461cbe2408d858c4b0a9%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637356949086641203&sdata=UBxrEMtqh3Qo7%2B45xA9%2Fz6lqQIXD3LGvdMyVCNGOwSA%3D&reserved=0

\newpage
# References