---
title: "GCB submission notes"
output: pdf_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[*author instructions*](https://onlinelibrary-wiley-com.smithsonian.idm.oclc.org/page/journal/13652486/homepage/forauthors.html)

# ORCHIDs

Ben: 0000-0001-9525-4633

Valentine: 0000-0002-4519-481X


# submission questions


## What is the scientific question you are addressing?

How do nine major annual autotrophic carbon fluxes in forests vary globally with respect to latitude and climate?

## What is/are the key finding(s) that answers this question

Nine major carbon fluxes decreases linearly and roughly in proportion to one another across latitudes. Temperature variables are the best univariate climate predictors, with additional effects of moisture availability. The influence of climate on carbon fluxes within the growing season was small but significant for a number of fluxes.

##    Why is this work important and timely?

Forests will strongly influence climate change, and cohesive understanding of their carbon fluxes vary with respect to climate is foundational to understanding global-scale forest C cycling and benchmarking the models used to predict forest responses and feedbacks to accelerating climate change.

##    Does your paper fall within the scope of GCB; what biological AND global change aspects does it address?

The paper falls within the scope of GCB addressing how forest carbon fluxes (biological aspect) relate to climate (global change aspect).

##    What are the three most recently published papers that are relevant to this question? This information will assist the Editors in selecting reviewers.

Collalti, A., Ibrom, A., Stockmarr, A., Cescatti, A., Alkama, R., Fernández-Martínez, M., Matteucci, G., Sitch, S., Friedlingstein, P., Ciais, P., Goll, D. S., Nabel, J. E. M. S., Pongratz, J., Arneth, A., Haverd, V., & Prentice, I. C. (2020). Forest production efficiency increases with growth temperature.Nature510Communications,11(1), 5322.

Smith, M. N., Taylor, T. C., Haren, J. van, Rosolem, R., Restrepo-Coupe, N., Adams, J., Wu, J., Oliveira, R. C. de, Silva, R. da, Araujo, A. C. de, Camargo, P. B. de, Huxman, T. E., & Saleska, S. R. (2020).  Empirical evidence for resilience of tropical forest photosynthesis in a warmer world.Nature Plants,6(10),6771225–1230

Sullivan et al (2020). Long-term thermal sensitivity of Earth’s tropical forests. Science, 368(6493), 869–874. 

# Data availability statement

Data were obtained from the open access ForC database (v3.0, archived on Zenodo with DOI 10.5281/zenodo.3403855). Code and data necessary to reproduce all results are available through GitHub (https://github.com/forc-db/Global_Productivity) and archived in Zenodo (DOI: TBD).